# Generated by Django 3.0.5 on 2024-06-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20240605_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='by',
            field=models.CharField(default='The teacher', max_length=30, null=True),
        ),
    ]
