# Generated by Django 3.0.5 on 2024-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20240606_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('by', models.CharField(default='The student', max_length=30, null=True)),
                ('homework_teacher', models.CharField(default='The Teacher', max_length=30, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('uploaddate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
